# Generated by Django 5.1.5 on 2025-05-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_postcategory_threadcategory_thread_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadcategory',
            options={'ordering': ['name'], 'verbose_name': 'Thread category', 'verbose_name_plural': 'Thread categories'},
        ),
    ]
