# Generated by Django 5.2.1 on 2025-05-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-status']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['applied_on']},
        ),
    ]
