# Generated by Django 5.1.6 on 2025-02-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='entry',
            field=models.TextField(null=True),
        ),
    ]
