# Generated by Django 5.1.5 on 2025-05-15 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_profile_slug'),
        ('wiki', '0006_alter_article_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_comment_author', to='user_management.profile'),
        ),
    ]
