# Generated by Django 5.2.1 on 2025-05-13 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='user_management.profile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='header_image'),
        ),
    ]
