# Generated by Django 5.2.1 on 2025-05-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author_alter_article_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='entry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
